---
- hosts: webservers
  remote_user: root
  tasks:
   - name: Install yum packages
     yum: name={{item}} state=installed
     with_items:
         - readline-devel
         - pcre-devel
         - openssl-devel
         - gcc
         - wget
     when: ansible_os_family == 'RedHat'


   - name: Install apt Packages
     apt: name={{item}} state=installed
     with_items:
         - libreadline-dev
         - libncurses5-dev
         - libpcre3-dev
         - libssl-dev
         - perl
         - make
         - build-essential
         - wget
     when: ansible_os_family == 'Debian'


   - name: Download OpenResty Package
     shell: wget https://openresty.org/download/openresty-1.9.7.4.tar.gz chdir=/tmp


   - name: Deflating Openresty Packages
     shell: tar -xvf openresty-1.9.7.4.tar.gz chdir=/tmp

   - name: Configuring OpenResty
     shell: ./configure --without-lua_cjson --without-lua_redis_parser --without-lua_rds_parser --without-lua_resty_dns --without-lua_resty_memcached --without-lua_resty_redis --without-lua_resty_mysql --without-lua_resty_upload --without-lua_resty_upstream_healthcheck --without-lua_resty_string --without-lua_resty_websocket --without-lua_resty_lock --without-lua_resty_lrucache --without-lua_resty_core --without-lua51 --without-select_module --without-poll_module --with-luajit --with-pcre --with-pcre-jit chdir=/tmp/openresty-1.9.7.4/

   - name: Installing OpenResty
     shell: make && make install chdir=/tmp/openresty-1.9.7.4/
